youtube.api.key=AIzaSyB1yFmue21_dN7msmcWtCH_1s1RzOY4Igk
youtube.api.base.url=https://www.googleapis.com/youtube/v3
youtube.search.query=Bruno Mars, Shakira, Pitbull, Maroon 5, Olivia Rodrigo
youtube.search.maxResults=5
db.url=jdbc:sqlite:data/youtube.db
