youtube.api.key=AIzaSyB1yFmue21_dN7msmcWtCH_1s1RzOY4Igk
youtube.api.base.url=https://www.googleapis.com/youtube/v3
youtube.search.query=Bruno Mars
youtube.search.maxResults=3
db.url=jdbc:sqlite:data/youtube.db
